name: cbo-telegram-bot
region: nyc
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: YOUR_GITHUB_USERNAME/cbo-telegram-bot
  http_port: 3000
  instance_count: 1
  instance_size_slug: professional-xs
  name: cbo-bot
  run_command: npm start
  source_dir: /
  envs:
  - key: TELEGRAM_BOT_TOKEN
    scope: RUN_TIME
    value: ${TELEGRAM_BOT_TOKEN}
  - key: NODE_ENV
    scope: RUN_TIME
    value: production
  - key: PORT
    scope: RUN_TIME
    value: "3000"
  - key: WEBHOOK_URL
    scope: RUN_TIME
    value: ${APP_URL}