name: cbo-demo-miniapp
region: nyc
services:
- environment_slug: node-js
  github:
    branch: master
    deploy_on_push: true
    repo: ForkIt369/cbo-telegram-bot
  build_command: npm ci --force && npm run build
  run_command: node src/webhook-server.js
  http_port: 3003
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: telegram-bot
  envs:
  - key: NODE_ENV
    value: production
    scope: RUN_AND_BUILD_TIME
  - key: PORT
    value: "3003"
    scope: RUN_AND_BUILD_TIME
  - key: TELEGRAM_BOT_TOKEN
    value: "8139049417:AAEfmoNXmUhz4y842SdtKL8SjPwgYzIXDNI"
    scope: RUN_TIME
    type: SECRET
  - key: MAIN_BOT_TOKEN
    value: "8139049417:AAEfmoNXmUhz4y842SdtKL8SjPwgYzIXDNI"
    scope: RUN_TIME
    type: SECRET
  - key: SDK_BOT_TOKEN
    value: "8171421117:AAE4FAJW2sxUWQyoP4Z7g9xW4SfXlZqJB0A"
    scope: RUN_TIME
    type: SECRET
  - key: ANTHROPIC_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: WEBHOOK_URL
    value: "https://cbo-mcp-system-hs2sx.ondigitalocean.app"
    scope: RUN_TIME
  - key: ENABLE_MCP_TOOLS
    value: "true"
    scope: RUN_AND_BUILD_TIME